version: '3'

services:

  #############################################################################
  ###### Data Bases ###########################################################
  #############################################################################

  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=Run_App
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=25032001
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - backend

  #############################################################################
  ###### Services #############################################################
  #############################################################################

  profile-service:
    container_name: profile-service
    image: denpool/profile-service:test
    restart: always
    ports:
      - "4000:4000"
    networks:
      - backend
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8887
      - SPRING_CLOUD_CONFIG_PROFILE=docker
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started


  social-service:
    container_name: social-service
    image: denpool/social-service:0.0.2
    ports:
      - "5000:5000"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8887
      - SPRING_CLOUD_CONFIG_PROFILE=docker
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started
    networks:
      - backend


  guild-service:
    container_name: guild-service
    image: denpool/guild-service:test
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8887
      - SPRING_CLOUD_CONFIG_PROFILE=docker
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started


  shoes-service:
    container_name: shoes-service
    image: denpool/shoes-service:test
    restart: always
    ports:
      - "2222:2222"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8887
      - SPRING_CLOUD_CONFIG_PROFILE=docker
    networks:
      - backend
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started


  achievement-service:
    container_name: achievement-service
    image: denpool/achievement-service:test
    ports:
      - "3333:3333"
    networks:
      - backend
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8887
      - SPRING_CLOUD_CONFIG_PROFILE=docker
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started


  story-management-service:
    container_name: story-management-service
    image: denpool/story-management-service:test
    ports:
      - "4444:4444"
    networks:
      - backend
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8887
      - SPRING_CLOUD_CONFIG_PROFILE=docker
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started


  story-progress-service:
    container_name: story-progress-service
    image: denpool/story-progress-service:test
    ports:
      - "5555:5555"
    networks:
      - backend
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8887
      - SPRING_CLOUD_CONFIG_PROFILE=docker
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started


  workout-service:
    container_name: workout-service
    image: denpool/workout-service:test
    ports:
      - "7000:7000"
    networks:
      - backend
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8887
      - SPRING_CLOUD_CONFIG_PROFILE=docker
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started


  discovery-service:
    container_name: discovery-service
    image: denpool/discovery-service
    restart: always
    ports:
      - "7777:8761"
    networks:
      - backend


  storage-service:
    container_name: storage-service
    image: denpool/storage-service:0.0.1
    restart: always
    networks:
      - backend
    ports:
      - "6500:6500"
    depends_on:
      discovery-service:
        condition: service_started


  event-service:
    container_name: event-service
    image: denpool/event-service:test
    ports:
      - "9000:9000"
    networks:
      - backend
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8887
      - SPRING_CLOUD_CONFIG_PROFILE=docker
    depends_on:
      config-service:
        condition: service_started

  config-service:
    container_name: config-service
    image: denpool/config-service:0.0.1
    networks:
      - backend
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/RunAppHackaton/MicroservicesConfigs.git
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "5656:8080"
    networks:
      - backend

networks:
  backend:
volumes:
  db-data: